[profile.default]
libs = ["lib"]
remappings = [
  "@openzeppelin/=lib/openzeppelin/",
  "@account-abstraction/=lib/account-abstraction/",
  "account-abstraction/=lib/account-abstraction/contracts/",
  "account-abstraction-v07/=lib/account-abstraction-v07/contracts/",
  "solady/=lib/solady/src/",
  "solady-dc09481/=lib/solady-dc09481/src/",
  "solady-6c2d0da/=lib/solady-6c2d0da/src/"
]
src = "src"
out = "out"

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
holesky = "${HOLESKY_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
holesky = { key = "${ETHERSCAN_API_KEY}" }