[profile.default]
libs = ["lib"]
remappings = [
  "solady/=lib/solady/src/",
  "solady-dc09481/=lib/solady-dc09481/src/",
]
src = "src"
out = "out"

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
holesky = "${HOLESKY_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
holesky = { key = "${ETHERSCAN_API_KEY}" }