name: Bench

on: workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup

  bench:
    name: Benchmark
    needs: install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        transport-mode: ['http', 'webSocket']
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Bench
        run: pnpm bench:ci
        env:
          VITE_ANVIL_BLOCK_NUMBER: ${{ vars.VITE_ANVIL_BLOCK_NUMBER }}
          VITE_ANVIL_BLOCK_TIME: ${{ vars.VITE_ANVIL_BLOCK_TIME }}
          VITE_ANVIL_FORK_URL: ${{ vars.VITE_ANVIL_FORK_URL }}
          VITE_NETWORK_TRANSPORT_MODE: ${{ matrix.transport-mode }}
      - name: Report
        run: pnpm bun ./.github/scripts/bench.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
