name: Main

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
        pnpm-version: [7]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node-version }}
      - name: Cache pnpm
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: pnpm-
      - name: Cache node_modules
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: |
            dist
            node_modules
            playgrounds/**/node_modules
            site/node_modules
          key: modules-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: pnpm i
      - name: Link Dependencies
        if: steps.cache-node-modules.outputs.cache-hit == 'true'
        run: pnpm dev

  lint:
    name: Lint
    needs: install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
        pnpm-version: [7]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            dist
            node_modules
            playgrounds/**/node_modules
            site/node_modules
          key: modules-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Link
        run: pnpm dev
      - name: Check types
        run: pnpm typecheck
      - name: Lint & format code
        run: pnpm format & pnpm lint:fix
      - name: Commit
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git add .
          if [ -z "$(git status --porcelain)" ]; then
            echo "no formatting changed"
            exit 0
          fi
          git commit -m "chore: format"
          git push
          echo "pushed formatting changes https://github.com/$GITHUB_REPOSITORY/commit/$(git rev-parse HEAD)"

  build:
    name: Build
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
        pnpm-version: [7]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            dist
            node_modules
            playgrounds/**/node_modules
            site/node_modules
          key: modules-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Build
        run: pnpm build
      - name: Check size
        run: pnpm size
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
          CI_BRANCH_BASE: main

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
        pnpm-version: [7]
        shard: [1, 2, 3]
        total-shards: [3]
        transport-mode: ['http', 'webSocket']
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            dist
            node_modules
            playgrounds/**/node_modules
            site/node_modules
          key: modules-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          profile: minimal
          override: true
      - name: Install Anvil
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Launch Anvil
        run: anvil --fork-url $VITE_ANVIL_FORK_URL --fork-block-number $VITE_ANVIL_BLOCK_NUMBER --block-time $VITE_ANVIL_BLOCK_TIME &
        env:
          VITE_ANVIL_BLOCK_NUMBER: ${{ secrets.VITE_ANVIL_BLOCK_NUMBER }}
          VITE_ANVIL_BLOCK_TIME: ${{ secrets.VITE_ANVIL_BLOCK_TIME }}
          VITE_ANVIL_FORK_URL: ${{ secrets.VITE_ANVIL_FORK_URL }}
      - name: Test
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 20
          max_attempts: 3
          command: pnpm test:ci --shard=${{ matrix.shard }}/${{ matrix.total-shards }}
        env:
          ALCHEMY_ID: ${{ secrets.ALCHEMY_ID }}
          VITE_ANVIL_BLOCK_NUMBER: ${{ secrets.VITE_ANVIL_BLOCK_NUMBER }}
          VITE_ANVIL_BLOCK_TIME: ${{ secrets.VITE_ANVIL_BLOCK_TIME }}
          VITE_ANVIL_FORK_URL: ${{ secrets.VITE_ANVIL_FORK_URL }}
          VITE_NETWORK_TRANSPORT_MODE: ${{ matrix.transport-mode }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  bench:
    name: Benchmark
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
        pnpm-version: [7]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            dist
            node_modules
            playgrounds/**/node_modules
            site/node_modules
          key: modules-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          profile: minimal
          override: true
      - name: Install Anvil
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Launch Anvil
        run: anvil --fork-url $VITE_ANVIL_FORK_URL --fork-block-number $VITE_ANVIL_BLOCK_NUMBER --block-time $VITE_ANVIL_BLOCK_TIME &
        env:
          VITE_ANVIL_BLOCK_NUMBER: ${{ secrets.VITE_ANVIL_BLOCK_NUMBER }}
          VITE_ANVIL_BLOCK_TIME: ${{ secrets.VITE_ANVIL_BLOCK_TIME }}
          VITE_ANVIL_FORK_URL: ${{ secrets.VITE_ANVIL_FORK_URL }}
      - name: Bench
        run: pnpm bench:ci --changed
        env:
          ALCHEMY_ID: ${{ secrets.ALCHEMY_ID }}
          VITE_ANVIL_BLOCK_NUMBER: ${{ secrets.VITE_ANVIL_BLOCK_NUMBER }}
          VITE_ANVIL_BLOCK_TIME: ${{ secrets.VITE_ANVIL_BLOCK_TIME }}
          VITE_ANVIL_FORK_URL: ${{ secrets.VITE_ANVIL_FORK_URL }}
          VITE_NETWORK_TRANSPORT_MODE: ${{ matrix.transport-mode }}
      - name: Report
        run: node -r esbuild-register ./.github/scripts/bench.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
